DROP TRIGGER IF EXISTS check_station_lines_position_is_valid ON station_lines;
DROP FUNCTION IF EXISTS check_station_lines_position();
DROP TABLE IF EXISTS amenity_locations;
DROP TABLE IF EXISTS amenity_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS amenities;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS station_lines;
DROP TABLE IF EXISTS lines;
DROP TABLE IF EXISTS stations;