CREATE TABLE locations (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR,
    address VARCHAR,
    station VARCHAR,
    minutes_to_walk INT,
    FOREIGN KEY (station) REFERENCES stations(name)
);