CREATE TABLE locations (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    address VARCHAR NOT NULL,
    station VARCHAR NOT NULL,
    minutes_to_walk INT NOT NULL,
    FOREIGN KEY (station) REFERENCES stations(name)
);